### ISSUE TITLE
Dataflow: The location field of LaunchFlexTemplateRequest builder is not working

### ISSUE THREAD

**Issue by vanb** [googleapis/java-dataflow#64]
The location field of LaunchFlexTemplateRequest builder is not working

I created a dataflow job with **us-east4** as the location of the `LaunchFlexTemplateRequest`.
However, the job region becomes **us-central1**.

This is the identical experience to the issue reported in the node client library.
https://github.com/googleapis/nodejs-dataflow/issues/19

#### Code example

```java
try (FlexTemplatesServiceClient flexTemplatesServiceClient = FlexTemplatesServiceClient.create()) {
      LaunchFlexTemplateRequest request =
              LaunchFlexTemplateRequest.newBuilder()
                      .setValidateOnly(false)
                      .setProjectId(projectId)
                      .setLocation("us-east4")
                      .setLaunchParameter(LaunchFlexTemplateParameter.newBuilder()
                              .setJobName(jobName)
                              .setContainerSpecGcsPath(gcsPath)
                              .putParameters("inputFile", inputFile)
                              .putParameters("outputTable", outputTable)
                              .setEnvironment(FlexTemplateRuntimeEnvironment.newBuilder()
                                      .setServiceAccountEmail(serviceAccountEmail)
                                      .setSubnetwork(subnetwork)
                                      .build())
                              .build())
                      .build();

      LaunchFlexTemplateResponse response = flexTemplatesServiceClient.launchFlexTemplate(request);
}
```

#### Environment details

OS: macOS Big Sur 11.5.2

Java: openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07)
OpenJDK 64-Bit Server VM GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07, mixed mode, sharing)

Dataflow version: com.google.cloud:google-cloud-dataflow:0.2.2

**Comment by meredithslota** [comment]
We've identified similar issues in other repos and have escalated this to the API service team since it's not a language-specific library issue. Here are the related issues: 

- https://github.com/googleapis/python-dataflow-client/issues/31: ListJobsRequest is not using the 'location' filter #31
- https://github.com/googleapis/python-dataflow-client/issues/25: Support for locations in the launch_template method #25
- https://github.com/googleapis/nodejs-dataflow/issues/19: The location option of launchFlexTemplate is not working #19
- https://github.com/googleapis/java-dataflow/issues/64: Dataflow: The location field of LaunchFlexTemplateRequest building is not working #64
- https://github.com/googleapis/google-cloud-dotnet/issues/7038: ListJobsAsync() returns only us-central1 jobs #7038 (context from issue is that the `location` parameter isn't working)

Marking this as a P1 bug w/ `external` label.

**Comment by bbhoss** [comment]
@vanb were you able to find any workaround? Running into the same issue :(

**Comment by vanb** [comment]
> @vanb were you able to find any workaround? Running into the same issue :(

A workaround I finally found was to fallback to "Google API Client" libraries instead of these newer "Cloud Client" libraries.
https://cloud.google.com/apis/docs/client-libraries-explained

**Comment by bbhoss** [comment]
@meredithslota can you provide an update to this issue? Is there a Google Issue Tracker ticket we can follow? If not should we create one? This is currently a blocker for me and it would be nice to get a status update.

**Comment by bbhoss** [comment]
I couldn't find an existing issue in the Google Issue Tracker so I created one [here](https://issuetracker.google.com/issues/208105329). I suggest starring this issue to anyone else that runs across this problem, hopefully it will get some attention from Google soon.

**Comment by davidcavazos** [comment]
Hearing back from the product team, this issue should now be fixed on the latest version of the library.

I'm closing this, but feel free to re-open if the problem still persists.
